### ISSUE TITLE
Public WSRegistry via port 8080

### ISSUE THREAD

**Issue by thanhnh-infinity** [phylotastic/phylotastic#100]

**Comment by abusalehmdtayeen** [comment]
Web Service registry is now public via http://phylo.cs.nmsu.edu:8080/WSRegistry/

**Comment by arlin** [comment]
I could not log in.  I tried to add a new account, but got the message that my name and email were already in use. 
![screen shot 2016-02-01 at 4 28 35 pm](https://cloud.githubusercontent.com/assets/1659198/12731877/f622b9cc-c900-11e5-8c6b-6f2929dd44d5.png)

So I tried to retrieve the password for the account "arlin", but that failed as well: 

![screen shot 2016-02-01 at 4 30 02 pm](https://cloud.githubusercontent.com/assets/1659198/12731911/233b4bf4-c901-11e5-938e-73a308951943.png)

**Comment by epontell** [comment]
This is what I get when I try to create an account (mail server misconfigured?)

Enrico

--------------------
College of Arts & Sciences
New Mexico State University
Las Cruces, NM 88003

**Comment by thanhnh-infinity** [comment]
@epontell  : Could you re-try to sign in again ? I think it is ok. You created an account but should wait for approval from admin

@arlin  : I checked and saw that you have account already.  I updated already your account : arlin and password is arlin. Could you please re-login again ?

**Comment by arlin** [comment]
yes, this worked, thanks.

On Feb 1, 2016, at 4:51 PM, Thanh Nguyen <notifications@github.com<mailto:notifications@github.com>> wrote:


@epontell<https://github.com/epontell> : Could you re-try to sign in again ? I think it is ok. You created an account but should wait for approval from admin

@arlin<https://github.com/arlin> : I checked and saw that you have account already. I updated already your account : arlin and password is arlin. Could you please re-login again ?

—
Reply to this email directly or view it on GitHub<https://github.com/phylotastic/phylotastic/issues/100#issuecomment-178211687>.

------------
Arlin Stoltzfus (arlin@umd.edu<mailto:arlin@umd.edu>)
Research Biologist, NIST; Fellow, IBBR; Adj. Assoc. Prof., UMCP
IBBR, 9600 Gudelsky Drive, Rockville, MD, 20850
tel: 240 314 6208; web: www.molevol.org<http://www.molevol.org>
