### ISSUE TITLE
ask OpenTree about limits on large trees

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#109]
The gitter room is a good place to start.  https://gitter.im/OpenTreeOfLife/public

**Comment by abusalehmdtayeen** [comment]
I posted a question with the following example in https://gitter.im/OpenTreeOfLife/public
Example of Large Tree Exception from OpenTreeOfLife: 
To get the subtree of a node with ottId:304358 (taxonName: Eukaryota) using the OpenTreeOfLife API gives "IllegalArgumentException" with message:"Requested tree is larger than currently allowed by this service (25000 tips). For larger trees, please download the full tree directly from: http://files.opentreeoflife.org/trees/".

**Comment by arlin** [comment]
Are we done with this @abusalehmdtayeen?   I think we know now what the limits are.

**Comment by abusalehmdtayeen** [comment]
yes, we are done.
