### ISSUE TITLE
audio setup for NMSU

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#129]
set up a system with microphones, speakers and webcam to allow effective videoconferencing (good views of participants, no audio feedback)

**Comment by hdliv** [comment]
@arlin should this be moved to in review?

**Comment by hdliv** [comment]
@thanhnh-infinity i am assigning this to you, but it can be anyone.  We would like to see all three of you in our meetings :) :)

**Comment by hdliv** [comment]
@arlin I think this is OK.  Moving to In Review
