### ISSUE TITLE
Build Google OAuth 2.0 Client

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#139]
Build Google OAuth 2.0 Client on Google Cloud Platform. After this step we will have client ID, client secret from Google that allow Mobile, Phylotastic server and Portal are able to work on credential together.

**Comment by ducvan0212** [comment]
Can anyone share credentials of google app for me?

**Comment by ducvan0212** [comment]
By the way, I am also in need of an email that is used to send notifications to users.

**Comment by thanhnh-infinity** [comment]
ClientID : 936627843472-tbvfhfohauanrehv1l94a6lrj5lvq0r3.apps.googleusercontent.com

**Comment by ducvan0212** [comment]
Client secret?

**Comment by thanhnh-infinity** [comment]
Client secret was sent by email.

**Comment by ducvan0212** [comment]
Received but I got error 'omniauth: (google) Request phase initiated.'. I guess @thanhnh-infinity forgot enable requests from web. Please update the google app. Thanks.

**Comment by thanhnh-infinity** [comment]
Hi Van, 
1. The ClientID : 936627843472-tbvfhfohauanrehv1l94a6lrj5lvq0r3.apps.googleusercontent.com is generated for Web Application. All kinds of http request are enabled for this client ID. Attached file is my configuration for this key on Google

(https://raw.githubusercontent.com/phylotastic/Pt_Mobile_Application/master/test/images/ClientID.png)

I generated particular key for iOS application and it have worked normally (still running Phylotastic mobile app)

2. In the case that, you are not able  to use this. I generated another key call API_KEY. This is secret key so I will send you by email. At the moment, I have only allowed request comes from : phylo.cs.nmsu.edu:3000 or localhost:3000 can use API inside.
(https://raw.githubusercontent.com/phylotastic/Pt_Mobile_Application/master/test/images/API_KEY.png)

So, if you have any questions or problems, please let me know.

**Comment by ducvan0212** [comment]
Authorized JavaScript origins: http://phylo.cs.nmsu.edu:3000
Authorized redirect URIs: http://phylo.cs.nmsu.edu:3000/users/auth/google_oauth2/callback

Enable Contact and Google+ API

I set up my own app and the server is able to log in by google account. I am not sure how OAuth2 works with API_KEY as you set up in opt 2 so maybe it is not necessary for now because OAuth2 requires only Cliend ID and Client secret.

So please make changes as I mentioned before and then I will migrate from my app to your app credentials. Anw, thank you!

**Comment by thanhnh-infinity** [comment]
Please recheck again

**Comment by ducvan0212** [comment]
Got this error
![screen shot 2016-04-07 at 12 36 42 pm](https://cloud.githubusercontent.com/assets/1614884/14362595/71a2c3a4-fcbd-11e5-8418-d6f485011c45.png)

Check https://github.com/NREL/api-umbrella/issues/44 in last comment please

**Comment by thanhnh-infinity** [comment]
Check again Van.

**Comment by ducvan0212** [comment]
Succeeded!
