### ISSUE TITLE
sign up team member for github

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#14]
get everyone on the design team on github, and recommend some way for everyone to stay notified

**Comment by arlin** [comment]
and waffle.io

**Comment by arlin** [comment]
Enrico, as your people are already working on issues, I think it is time to get them signed up on github and waffle.   Let me know their github ids and I can add them there.

**Comment by epontell** [comment]
Two RAs are signed up (Van and Thanh); third one will not arrive until 8/17 (Abu Saleh)

**Comment by arlin** [comment]
signed up 5 members of design team.  All members of the current design team are signed up.  We can close this.
