### ISSUE TITLE
followup on ToolsForTreeOfLife.Jul7-8 opportunity

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#140]
see email of March 15 from LM.  possibility to send someone (@hdliv?) to workshop in Maine on  next-gen phenomics tools for the tree of life.  

see https://cms.usm.maine.edu/bio/ngp

**Comment by hdliv** [comment]
@arlin You were going to speak with someone there to have more information.  Were you able to?

**Comment by hdliv** [comment]
@arlin just checked with Lisa Moore and there are still spots available

**Comment by arlin** [comment]
did you sign up for this?  I'm not sure it's the best use of our limited travel budget.  Let's discuss and make a decision.

**Comment by epontell** [comment]
Do they actually give $750 to each participant? The would offset most of the travel costs

**Comment by hdliv** [comment]
@arlin @epontell 
i didnt sign up for it, then I did since it was a ticket.  I would only go if there is funding...but it seems that everyone is funded.  we do need to pay 50 bucks to hold a spot.  we can ask Lisa Moore again ...

**Comment by hdliv** [comment]
@arlin @epontell 

I contacted the secretary to verify the funding

**Comment by hdliv** [comment]
@arlin @epontell  I contacted the organizer and they do provide the funding.

**Comment by arlin** [comment]
@hdliv and I discussed this.  It looks to me like a rather lightweight pro forma meeting, rather than a serious outreach effort.   However, this may be a good way to make connections and for @hdliv to explore large phenomics datasets.  So, I'm leaving it up to him whether he wants to devote 2 days to this.
