### ISSUE TITLE
TDWG plan!

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#143]
TDWG (Costa Rica, 5-9 December) will be an opportunity for us to brainstorm and get feedback from people who are interested in data integration.  I'd like to make a plan to present there.  http://www.tdwg.org/conference2016/

**Comment by arlin** [comment]
deadline for abstract submission is 6 September 2016.

**Comment by hdliv** [comment]
@arlin @bomeara @epontell @dimus Just a reminder, the deadline is less than a month away

**Comment by arlin** [comment]
we decided that @hdliv would assess whether this is a good meeting for him.  if not, then we will either skip it, or ask @dimus to present.

**Comment by hdliv** [comment]
we will not participate in TDWG this year.  closing
