### ISSUE TITLE
draft metadata model

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#145]
draft a metadata model for trees returned by phylotastic system.  consult available information on "MIAPA" proposed minimal information standard.

**Comment by arlin** [comment]
see https://github.com/miapa

**Comment by hdliv** [comment]
this should also incorporate #193

**Comment by arlin** [comment]
@hdliv and I put  a draft metadata model here: https://github.com/phylotastic/phylotastic/blob/master/design/metadata_model.md

Here is an example of what the tree metadata serialization might look like: 

https://raw.githubusercontent.com/phylotastic/phylotastic/master/design/metadata.json

**Comment by arlin** [comment]
So, I'm going to close this.  We have a draft model.  It addresses phylotastic/phylotastic-portal#193.  

 Now, the next step is to start implementing it in the portal, which is a separate issue.
