### ISSUE TITLE
Create 'interesting' teaching exercises

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic#148]
We should create general 'interesting' phylogenetic examples, i.e. re-invasion of marine mammals to the water

**Comment by hdliv** [comment]
To finish this, we will use some of the information from a query to Listserv's

**Comment by arlin** [comment]
@epontell has provided me (privately) with a list of teachers will to test-drive.  But I think we will need to feed them examples.  I have contacted a colleague who teaches mostly at the grad level, who expressed interest previously.

**Comment by arlin** [comment]
@hdliv, we talked about this today-- focus on just 2 examples, and keep them simple (<20 OTUs).  We'll use these to show potential collaborators what we can do.

**Comment by hdliv** [comment]
@arlin should we make a new folder or place these examples in testing, outreach or use_cases

**Comment by arlin** [comment]
@hdliv, I just finished re-organizing some of the directories with use-cases and test data.  This material is in phylotastic/phylotastic.  The test data directory contains input data (and sometimes expected outputs) for testing.  

The teaching examples that you are describing do not exactly fit in either the category of testing or the category of use_cases.  I would suggest to create a new directory phylotastic/phylotastic/exercises or something like that.

**Comment by hdliv** [comment]
@arlin will do

**Comment by hdliv** [comment]
@arlin I have added two different exercises under phylotastic/phylotastic/exercises

**Comment by arlin** [comment]
@hdliv, those are awesome!  this is exactly what we need to show people what is possible.  i wonder if there is some way we can produce a static version that has the clickable links to EOL.  this might make it more of a learning tool.

**Comment by hdliv** [comment]
@arlin that would be cool because we are currently only capable on the interactive version.  maybe this is something we should try to implement?

**Comment by arlin** [comment]
for the birds example, I would drop Caiman (not needed), and swap out Cervus canadensis for Cervus elaphas which has a better pic.
