### ISSUE TITLE
Set up service registry

### ISSUE THREAD

**Issue by epontell** [phylotastic/phylotastic#16]

**Comment by epontell** [comment]
Alternatives explored - SOAP vs HTTP based. Opted for HTTP based. Currently identifying platform to install and temporary hardware to use for initial setup

**Comment by epontell** [comment]
Student has started learning about WSDL and revisiting our previous work on ontologies in order to determine best structure for describing services

**Comment by arlin** [comment]
So far as I understand it, this task is done.  The service registry is already running and it is being used by multiple tools, right?  If so, please close this.
