### ISSUE TITLE
Select Members of the Design Team

### ISSUE THREAD

**Issue by epontell** [phylotastic/phylotastic#17]

**Comment by epontell** [comment]
Members of design team:
Luke Harmon
Karen
Brian
Dmitry
Arlin
Enrico
Brian
Ramona

**Comment by epontell** [comment]
Cyndy Parr / Schultz

**Comment by arlin** [comment]
I think we can close this issue when we get confirmation from each of these people that they want to be part of the design team.  I think that applies to everyone but Luke.  Enrico, can you follow up by contacting him?

**Comment by epontell** [comment]
Emails sent to Karen, Brian S., Ramona, and Luke. Tomorrow I would like to send out a Doodle poll to schedule a conversation that will introduce them to our use cases page and engage them in contributing to it. Would that be ok?

**Comment by epontell** [comment]
Forgot, send email also to Katja
