### ISSUE TITLE
figure out what "supporting trees" means

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#172]
What is the relationship of the trees in supporting studies to the induced subtree?

**Comment by mjy** [comment]
Do you have exemplar statements/citations for reference?

Some supporting trees may be trees used in a consensus tree.  Some supporting trees may be trees derived with other analytical methods that share "similar" support values on branches of interest.  Some might be trees drawn by hand many years ago. ... etc.

My gut feeling is that If you are looking for a "global" definition I think "supporting" means almost nothing, it may read something like:

> A supporting tree is a phylogenetic tree that the author feels corroborates the result identified by the author as being the "best" hypothesis of the evolution of a clade.

This is more or less tautological, but I'm not sure if you can make a stronger assumption than this. 

Perhaps supporting trees are trees that support the author's conclusion/hypotheses, but that are not "linked" to said conclusion (target tree) by a quantitative derivation.  This type of definition would, for example, exclude trees used to derive a concensus tree from being "supporting" trees- this is likely not a desirable outcome.

**Comment by arlin** [comment]
@mjy, this is actually a specific technical question about what OpenTree's interface means when it lists the "supporting studies" for an induced subtree (https://github.com/OpenTreeOfLife/germinator/wiki/Synthetic-tree-API-v3#induced_subtree).  The docs say that supporting studies are "studies that contribute trees that support nodes in the subtree" but after looking at a few I was confused.  This is probably just a matter of me not fully understanding what is going on under the hood at OpenTree.

**Comment by mjy** [comment]
@arlin Hehe- this actually crossed my mind shortly after I clicked submit.  I'll stop bouncing in out of context ;)

**Comment by arlin** [comment]
@mjy no problem, we like knowing that someone out there is paying attention
