### ISSUE TITLE
get community feedback on use-cases

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#20]
We want three things.  
1.  feedback on our initial list of cases, including comments on feasibility or importance, and descriptions of sub-cases and related cases. 

2. Any additional cases not listed.  I'm creating another ticket for this. 

3.  Critical-needs users.  We would like to identify users who have such a recurrent or high-volume need for phylotastic services that they would be willing to partner with us on development and testing.  For instance, do you offer a widely used genome annotation service that would benefit from an automatic source of species trees to use in reconciliation?   Do you have a website like EOL with thousands of taxon pages that might benefit from having trees?

**Comment by arlin** [comment]
I'm taking this out of the current Use Cases milestone.  We decided 7/21 that we do not need to get community feedback in the first round of the design process.

**Comment by hdliv** [comment]
@arlin we have received community feedback.  should this be moved to in review or maintained as backlog?

**Comment by hdliv** [comment]
I think we finished this.  moving to in review
