### ISSUE TITLE
fix portal address

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#201]
Due 5/24/2018.  Current portal address is phylo.cs.nmsu.edu:3000.  

Change this to portal.phylotastic.org.  This can be done handily with varnish (https://varnish-cache.org/docs/trunk/index.html)

**Comment by epontell** [comment]
can you check? should work

**Comment by arlin** [comment]
yes, the redirect works!  thanks.

**Comment by arlin** [comment]
actually the redirect works but it changes immediately back to phylo.cs.nmsu.edu:3000.  The problem is that this is what people are going to bookmark.  So then we are screwed if we change the server or just use a different port. 

Can we get the URL to persist?  @dimus says that Varnish can do this and that it won't screw up RESTful URLs either.

**Comment by arlin** [comment]
I think we also need to fix http://phylo.cs.nmsu.edu:8080/WSRegistry/, moving this to registry.phylotastic.org .

**Comment by dimus** [comment]
Port 80 needs to be open for varnish though on some machine

**Comment by arlin** [comment]
let's talk about this tomorrow.  Ideally we want to accommodate a scheme like this  
* www.phylotastic.org --> main web home
* registry.phylotastic.org --> the registry
* portal.phylotastic.org --> web portal
* testportal.phylotastic.org --> a test portal for new features 
* mobile.phylotastic.org --> mobile app info

**Comment by arlin** [comment]
@dimus, @epontell this is the one we are talking

**Comment by arlin** [comment]
@abusalehmdtayeen, you can close this when registry.phylotastic.org points to the registry web home.  That is the only thing that remains to be done on this ticket.

**Comment by arlin** [comment]
thanks, @abusalehmdtayeen
