### ISSUE TITLE
update embedded docs

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#202]
Due 5/24/2018.  Screencast is a separate ticket (phylotastic/phylotastic-portal#240).  Review all the other embedded documentation in the portal. 

- [x] hints and messages in main views
- [x] Help: FAQ
- [x] Help: User guide
- [x] About

**Comment by arlin** [comment]
I have checked the Help page and everything still looks good here.

**Comment by arlin** [comment]
About page, need to update roster and group photo.

**Comment by arlin** [comment]
Updated roster on About page.  Working on photo.

**Comment by arlin** [comment]
Added new photo, updated captions.

**Comment by arlin** [comment]
@ducvan0212, I edited the about view of the portal directly.  I hope this did not break anything.  Can you check this on your development server?

**Comment by ducvan0212** [comment]
@arlin I don't think there is any problem with your updates.

**Comment by arlin** [comment]
BTW, articles in English are confusing.  In standard English, the correct command is "Enter a name for the file".  However, when space is limited (e.g., road signs, dialog boxes), it is acceptable to leave out the articles, as in "Enter name for file."  But we need to choose one or the other.   What we want to avoid is only leaving out *some* of the articles, e.g., the following are not idiomatic: "Enter a name for file", "Enter name for the file."

**Comment by ducvan0212** [comment]
I will run through whole portal and make changes to follow just one convention. 

@arlin, I think the master branch is very behind the dev branch, some parts in master are no longer in dev.
