### ISSUE TITLE
services ready for publication

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#206]
Due 6/8/2018. 

Once the list of services has been decided (#205), make sure all of the services are documented fully and in a way that matches the functionality.

**Comment by arlin** [comment]
@abusalehmdtayeen, I talked to @epontell this morning about the best way to do this.  I think the smartest approach is to 
1. start with the existing web-services test suite from Jonathan (https://github.com/jar398/tryphy), 
2. expand that to cover any additional services (and update some outdated info)
3. make sure everything works
4. set this up as a CI regression test on the services directory.

**Comment by abusalehmdtayeen** [comment]
@arlin , Its already done. I used Jonathan's test suite as a base and extended it with new services and test cases. It is now integrated in Travis CI. You can view it here: https://travis-ci.org/phylotastic/phylo_webservices

**Comment by arlin** [comment]
That is great!  Can you confirm that you moved Jonathan's code into ./tests and updated it?

**Comment by arlin** [comment]
OK, I have done a superficial review of this and I'm convinced that we are doing a lot of testing .  I am going to make some tickets for additional fixes that can be done at any time in the future.
