### ISSUE TITLE
check your name, email affiliation

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#209]
In the manuscript, make sure your contact information is correct.  

- [x] @abusalehmdtayeen
- [x] @hdliv
- [x] @epontell
- [x] @bomeara
- [x] @lunasare
- [x] @ducvan0212
- [x] @dimus
- [x] @thanhnh-infinity

**Comment by abusalehmdtayeen** [comment]
@arlin, I have updated my name and email in the manuscript.

**Comment by arlin** [comment]
OK, checking this off for you as well as @LunaSare

**Comment by dimus** [comment]
@arlin, my affiliation is the correct one

**Comment by epontell** [comment]
affiliation is ok

**Comment by arlin** [comment]
@hdliv sorry, you've been gone so long I forgot who you are :-0

**Comment by LunaSare** [comment]
Thanks @arlin, everything is correct
