### ISSUE TITLE
set up input form for use cases

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#21]
Decide on the structure of a use-case, including required and optional fields.  

Set up an online form, using google forms or some other technology. 

This form will be used to gather use cases during the public comment period  on our use-case list.

**Comment by arlin** [comment]
Removed from milestone as per 7/21 meeting.  We will gather feedback from our experts in a less formal way.

**Comment by hdliv** [comment]
moving to in review.  we have the initial use cases already
