### ISSUE TITLE
implementation: service registry

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#210]
Describe the implementation of the services registry in the appropriate manuscript section.

**Comment by thanhnh-infinity** [comment]
@arlin @epontell : I have written main ideas for implementation of services registry part in the manuscript. I think now it contains all necessary features of registry that we want to present. I will keep putting the example of description language as 4 main parts of WSDL format.

**Comment by arlin** [comment]
Thanks, @thanhnh-infinity @epontell this is good.  I think everything up to the "We implemented ..." part is mostly about design considerations rather than implementation, and belongs in the earlier design section.  That is, there is an earlier section to enumerate the design requirements for the registry.  Could you reconcile these two parts of the manuscript?

**Comment by thanhnh-infinity** [comment]
@arlin Yes, I will move the part that is up to the "We implemented ..." to registry design section "Analysis and Design / Registry and Services". In addition, I can write more a little bit for implementation.

**Comment by thanhnh-infinity** [comment]
I added examples for 4 parts of WSDL file in the implementation of service registry. This part is ready for your review

**Comment by arlin** [comment]
Thanks @epontell I think we can go with the shortened version for now.
