### ISSUE TITLE
implementation: web services

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#211]
In the manuscript, complete the verbal description of each type of web service.  For each type, pick one service as an example and describe it with one or two sentences.

**Comment by abusalehmdtayeen** [comment]
@arlin , I have finished writing this section.

**Comment by arlin** [comment]
@abusalehmdtayeen, this is good.  This has just the right level of detail.  I will probably make some little changes and I might have some small questions for you. Thanks.
