### ISSUE TITLE
describe python library implementation

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#212]
In the Implementation section, libraries subsection, describe the implementation of the Python library.  Provide 
* a sentence or two listing what kinds of functionality are covered.  What services are wrapped? Are there multi-step workflows, and if so, what kind of workflow execution control is used?  
* a sentence about the architecture of the package, e.g., what kinds of files, how many, what documentation, what kind of package standard (if any) is followed.  
* 1 or 2 one-liners from the package showing what it does.

**Comment by abusalehmdtayeen** [comment]
yes, @arlin. I will follow the writing style of Luna.
