### ISSUE TITLE
describe r-phylotastic implementation

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#213]
In the Implementation section, libraries subsection, describe the implementation of the r-phylotastic library.   This should be just a few sentences.

**Comment by LunaSare** [comment]
Hi @arlin 
Going from last to first on the things you listed, I wrote rphylotastic's:
* availability
* one example showing how it works
* a sentence on its architecture: In here, I'm not sure how to cite these two:
 R Core Team. 2018. R: a language and environment for statistical computing. Vienna, Austria: R Foundation for Statistical Computing.
Jeroen Ooms (2014). The jsonlite Package: A Practical and Consistent Mapping Between JSON Data and R Objects. arXiv:1403.2805
In the coverage description, I'm unsure on how to code the % sign, so I just wrote "percent" for now.
* and the functionalities covered: I'm not completely sure what you mean by multi-step workflows in the context of an r package. should we relate it to phylotastic's portal workflows?

Let me know if I should add anything else :)

**Comment by arlin** [comment]
In principle, a phylotastic toolbox in R or Python or some other language might have a function that represents a multi-step workflow, e.g., get_scaled_OTtree_from_website would take a URL, scrape names, get OpenTree topology, then scale that.  However, none of the functions do that, right?

**Comment by arlin** [comment]
in LaTeX, escape the percent symbol by putting a back-slash in front of it

**Comment by arlin** [comment]
@LunaSare, I can explain how to do the bibliography thing.  For the Ooms 2014 paper, go to arxiv, click on the NASA ADS link in the right sidebar, then scroll down on that page, find a formatted BibTeX entry for the article, and copy that into the clipboard.   Go back to overleaf, click on "Project" in the top bar to expose the file hierarchy for the project.  Open the phylotastic-ms.bib file, and paste in the bibtex code for Ooms 2014.  The first field is the citation code.  To cite the paper, use `\cite{citation-code}`.

**Comment by arlin** [comment]
and here is a bibtex entry for R: 
`
@Manual{,
    title = {R: A Language and Environment for Statistical Computing},
    author = {{R Core Team}},
    organization = {R Foundation for Statistical Computing},
    address = {Vienna, Austria},
    year = {2013},
    url = {http://www.R-project.org/},
  }
`

**Comment by arlin** [comment]
@LunaSare, thanks.  You can close this ticket when the bibliography entries are done.

**Comment by LunaSare** [comment]
Thanks for the explanations @arlin! I added the bib entries. 
Also, yes, as far as I have seen, none of the rphylotastic functions have a multi-step workflow, as the one you described above. Also, I don't think we will need to develop anything like that for the r package in the future.
