### ISSUE TITLE
describe portal implementation

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#214]
In the Implementation: web portal section of the manuscript, describe the portal implementation, including web app framework, database, authentication, and anything else you think is important.  This should be about 1 paragraph.

**Comment by ducvan0212** [comment]
I am not sure how long you want me to describe the portal, so can @epontell and @arlin take a look at what I wrote? Please let me know if I need to add more details.

**Comment by arlin** [comment]
@ducvan0212, thanks.   What you described is the flow of operations in the user's experience of the portal.  This will be covered in the discussion.   What we need for this section is a paragraph about the implementation of the portal.  It should mention things like
* the application framework (Rails, etc)
* reliance on services for data, computation and managing lists.
* database (mysql?)  to store some things, but not everything.  the lists are stored in the list server. 
* embedded documentation

**Comment by ducvan0212** [comment]
@arlin I re-worked on the portal section. Can you please take a look again? Thank you.

**Comment by arlin** [comment]
OK, thanks.  I re-wrote this and hid some stuff that is not essential.  Thanks.  Closing this.
