### ISSUE TITLE
check 2.6 vs. 2.3 M species issue

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#220]
catalog of life.  1.9 M living species, the rest extinct.  

check the source.

**Comment by arlin** [comment]
The source for 2.6 M figure is that 2.6 M is the number of "tips" referenced in https://tree.opentreeoflife.org/about/synthesis-release/v9.1

Redelings and Holder (https://peerj.com/articles/3058/) refer to 2.4 M "leaves" but this was not the most recent taxonomy because they were trying to re-do the tree from Hinchliffe.  

@dimus, I am passing this ticket to you to declare what you think is the right number.   If you don't like us to say this number I can just say "over 2 million species".  

Once you tell me what to say, you can either change it in the text, or let me know and I will change it.

**Comment by dimus** [comment]
According to https://dx.doi.org/10.1371%2Fjournal.pbio.1001127 1.2 million species are in catalog. 
According to https://www.journals.uchicago.edu/doi/10.1086/693564 1.5 million species are in catalog.
Catalogue of Life 2018 edition has 1.8 million of extinct and extanct species presented and gives estimates 2.3 million of total described species.

**Comment by dimus** [comment]
other sources:
https://en.wikipedia.org/wiki/Global_biodiversity

And one oldish that we used at EOL says:
The total number of accepted described species in the
world is estimated to be close to 1,900,000, well above the
1,786,000 given in 2006. Worldwide,

http://www.environment.gov.au/system/files/pages/2ee3f4a1-f130-465b-9c7a-79373680a067/files/nlsaw-2nd-complete.pdf

**Comment by arlin** [comment]
I just changed this to "over 2 million" so that we don't have to address this issue.  At some point in time we might want to find out why OTT has 2.6 million species, but we don't need to know this for the manuscript.
