### ISSUE TITLE
r phylotastic real-life example for ms

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#227]
Our manuscript was criticized for not including real-life examples.  

Develop a real-life example using R phylotastic to include in the manuscript.  Think about what will interest MEE readers.  This can be something that is already in the documentation.

**Comment by abusalehmdtayeen** [comment]
@bomeara , any progress on the real-life example for the paper? I will convert your R script into python script once you are done. Please let me know when you finish. thanks.

**Comment by arlin** [comment]
@LunaSare has created a working example [here](https://github.com/phylotastic/rphylotastic/blob/master/data-raw/rphylotastic_examples.R).   I tested this and everything works!

**Comment by arlin** [comment]
next steps from f2f meeting: @bomeara @LunaSare @arlin will streamline this and make it more readable, then turn it over to Abu to make the Python version.

**Comment by arlin** [comment]
nice work @LunaSare and @bomeara
