### ISSUE TITLE
real-life python lib example for manuscript

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#228]
Our manuscript was criticized for not including real-life examples.  

Develop a real-life example using the python library to include in the manuscript.  Think about what will interest MEE readers.  This can be something that is already in the documentation.

**Comment by abusalehmdtayeen** [comment]
@arlin ,  I have written a script (with comments) using our python library to demonstrate the use case of getting trees from web pages.  Is this example good enough? I am putting it here because I am not sure where to include it in the manuscript.

```
#Load the 'json' module to handle json data format 
import json
#Load the main 'phylotastic_services' module to access the methods
import phylotastic_services

#Call the 'extract_names_URL' method to extract scientific names from a web page. The first parameter is the URL of the web page and second parameter is the source tool to be used for extraction 
extraction_result = phylotastic_services.extract_names_URL("https://en.wikipedia.org/wiki/Plain_pigeon", "gnrd")
#Retrieve the scientific names from the result returned by the method
extracted_names = json.loads(extraction_result)['scientificNames']

#Call the 'resolve_names_OT' method to clean the extracted scientific names
resolver_result = phylotastic_services.resolve_names_OT(extracted_names)
#Retrieve the resolved names from the result returned by the method
resolved_names = []
for result in json.loads(resolver_result)['resolvedNames']:
	resolved_names.append(result['matched_results'][0]['matched_name'])

#Call the 'get_tree_OpenTree' method to obtain a phylogenetic tree from the resolved names
tree_result = phylotastic_services.get_tree_OpenTree(resolved_names)
#Retrieve the tree in newick format from the result returned by the method
print json.loads(tree_result)['newick'] 
```

**Comment by arlin** [comment]
@abusalehmdtayeen, thanks!  Today we decided to present the same example in Python and R, so please work together with @bomeara and @LunaSare .

**Comment by abusalehmdtayeen** [comment]
Latest python example for manuscript.
```
import phylotastic_services
import json
from ete3 import Tree, NodeStyle, TreeStyle

birds_I_saw = [result['matched_names'][0]['scientific_name'] for result in json.loads(phylotastic_services.get_scientific_names(["Osprey", "House sparrow", "Mallard duck", "American Robin"]))['result']]
yellowstone_bird_list = json.loads(phylotastic_services.extract_names_URL("https://www.nps.gov/yell/learn/nature/upload/BirdChecklist2014.pdf"))['scientificNames']
yellowstone_bird_tree = json.loads(phylotastic_services.get_tree_OpenTree(yellowstone_bird_list,ottid=False))['newick']

t = Tree(yellowstone_bird_tree, format=1, quoted_node_names=True)
circular_style = TreeStyle()
circular_style.mode = "c" # draw tree in circular mode
for n in t.traverse():
    if n.is_leaf and n.name in birds_I_saw:
       n.set_style(NodeStyle(fgcolor="red",hz_line_color="red",size=12))
t.show(tree_style=circular_style)
```

**Comment by abusalehmdtayeen** [comment]
@arlin, I have finished making the python example corresponding to @LunaSare 's R example for the manuscript. You can close this issue after testing the example. To test the example, first copy the code from above and paste into a file named manuscript.py. Please make sure you have the latest phylotastic services python package [https://github.com/phylotastic/phylotastic_py] installed. Then just run the following command in your command prompt.
```
python manuscript.py
```

**Comment by abusalehmdtayeen** [comment]
The example output will look like the following.
![example.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55e77ef04a918e180047ade2/125516c66e82c728ace21e0d46ed8c9b2e928faccda5fd53b652fa912a5265296b51f67e72d0b17fba417f000a0e1ba917585f40feaa807da3a42062c80d55b98e30063e937f03a6aa8318b500bf25894a83bebe8949c9e03437aa.png)
