### ISSUE TITLE
fix phylomatic example on web site or remove

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#23]
Enrico noticed that the Phylomatic api call on the "web services" page at phylotastic.org is not working.  We get a 404 "not found" error. 

I'll write to Cam Webb to see what's up.  If we can't fix it, we can remove the link.

**Comment by epontell** [comment]
We were able to run - my student should be able to update the description

**Comment by arlin** [comment]
OK.  I guess you are ahead of me on this one.  I will re-assign it to you instead of me.   

FYI, Cam says that "The main page is: http://phylodiversity.net/phylomatic/ with directions for using the API there" but probably you know that already.

**Comment by epontell** [comment]
Will get Thanh to fix the description

**Comment by arlin** [comment]
This is fixed in the repo but the content has to get pushed to the web site.   See #4.
