### ISSUE TITLE
get flight information

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#230]
We need to plan for how much time we have on Sunday, March 3.  Please indicate the latest (affordable, convenient) flight that gets you home on Sunday. 
- [ ] Arlin
- [ ] Brian
- [x] Dima
- [x] Jodie

**Comment by jwiggi18** [comment]
I can get a flight out of El Paso at 2:52 PM.

**Comment by arlin** [comment]
thanks.  FYI, shuttle from Las Cruces takes an hour.

**Comment by dimus** [comment]
And my last flight from El Paso is also at 2:52PM! Apparently now there are direct flights from El Paso to Champaign-Urbana
