### ISSUE TITLE
workflow diagram 

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#246]
Make a workflow diagram that maps out options for inputs and outputs, along with important internal steps.  

This is for the revised manuscript.  

The workflow diagram would show steps in the user's workflow, allowing for various options in terms of the types of inputs.

**Comment by epontell** [comment]
New version of workflow diagram added to the comment response and uploaded into overleaf

**Comment by arlin** [comment]
![workflow](https://user-images.githubusercontent.com/1659198/66773835-00575180-ee8e-11e9-98d3-bd4031e73952.png)
