### ISSUE TITLE
initial web UI plan

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#27]
At our August 4 meeting, we decided that an initial target would be a web form that provides phylotastic functionality.  This can be done without waiting for the back-end system architecture to be designed.  We can use this to demonstrate various conditions and use-cases.  This ticket is about making a rough design, and deciding who is going to do this.

**Comment by epontell** [comment]
Who will do this?

**Comment by bomeara** [comment]
We could robustify datelife and do it through there: already takes list of taxa, returns tree

**Comment by bomeara** [comment]
But still need to finish integrating opentree data

**Comment by bomeara** [comment]
Include example with common name mapping: pig, dog, cat

**Comment by arlin** [comment]
Implement a small set examples that are easy to implement (low-hanging fruit) and show off the value of the system.  

1.  graphical: get tree from common names (pets)
2.  graphical: tree for IUCN red list species 
3.  same as above, but do it with an R script 
4.  character-mapping 
5.  scrape names from web page 
6.  tree for taxon, e.g., felidae

**Comment by bomeara** [comment]
I'm still fighting through getting a major chronogram into OpenTree to help with the back end of this. There have been a few issues. If you TNRS to open tree names, and throw out the names that don't match, the names that do match seem sometimes not to match (or even be acceptable).  Working around this, but still having upload issues.

**Comment by arlin** [comment]
I have proposed a plan for this and set up a repo (phylotastic/general-web-ui)

**Comment by arlin** [comment]
We just need to decide who is going to do this and get started.
