### ISSUE TITLE
contact collaborators

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#3]
Contact all the people who agreed to be involved in the proposal.  Ask them if they are still available.  Remind them of agreed to do.  Indicate what is coming up.

**Comment by epontell** [comment]
I can contact the NMSU Biology teacher

**Comment by arlin** [comment]
Done: Walls, Sidlauskas

**Comment by arlin** [comment]
Done: Haag, Paar.

**Comment by epontell** [comment]
Galves on board for outreach. No response yet from Nishiguchi

**Comment by arlin** [comment]
so, everyone has been contacted, and this can be closed.
