### ISSUE TITLE
mockup of initial demos

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#34]

**Comment by arlin** [comment]
I have drafted an initial mock-up of demos.  This is in our dropbox folder: 

Phylotastic/Design/initial_web_demo_mockup.pptx

I am about to go on vacation.  If someone wants to put this somewhere more accessible, for other team members, go ahead and do it.  I'll be back Sept 10.  

Brian's response to this is that the 6 demos that I outline are too much.  We are trying to put something out there soon, but this is too much to do, and we don't want to raise expectations too far initially.  

The next step for this is for the leadership team, or the design team, to review the mock-up at the next meeting (I'll be gone), decide on priorities (i.e., 2 or 3 demos that we want to support), and then start discussing requirements with the programmers so that they understand exactly what needs to be done.

**Comment by bomeara** [comment]
We might want to be careful about relying too much on sending stuff out to the programmers at this stage, as they don't really exist: there are postdoc candidates for Arlin and new students still learning about github, waffle.io, etc. with Enrico, not a team we can push requirements to and have them iterate on, in the way that bigger projects like iPlant, Arbor, or OpenTree have. I think to make progress at this stage it requires the senior folks doing coding (and this may continue through the project). Now, if we mean "programming team" is Dima to do name pulling from a website, me to do connection to OpenTree, etc., then I agree that settling on priorities and then sending that team to go do work is fine.

**Comment by arlin** [comment]
Please read it as if we are referring to roles and not people.  Presumably we will have some people like me working on testing and design that are not doing the implementations.  However, I don't imagine we will have programmers who are tackling issues but are not attending regular design team meetings and participating in analysis of requirements.  My (limited) experience with this is that for most issues it is more time-efficient to include programmers in meetings that cover upstream design steps than to have to (1) write a whole book to make an issue clear or (2) go back and forth in multiple iterations trying to resolve an issue that was not understand initially.   Enrico is the design team leader so I'll defer to him on this.

**Comment by arlin** [comment]
I just realized that this issue duplicates #27, or else could be considered a sub-task of #27.  I'm spoiled by Jira.  Does anyone know how to mark duplicates or sub-tasks in github or waffle?
