### ISSUE TITLE
Move legacy repos out of main phylotastic org

### ISSUE THREAD

**Issue by epontell** [phylotastic/phylotastic#37]
* Move old code to a deprecated section of git
* Explore use of VMs for sharing code?
* Commercial version of github?

**Comment by arlin** [comment]
Can we narrow this down to just the repo clutter issue?  I thought  that was the focus at the meeting.  I think the other two items should be put in backlog as possible things we might want to do at some point.  Any objections?

**Comment by bomeara** [comment]
I agree with arlin about scope. I've moved most of the old repos to a new phylotastic-legacy organization. There are a few I don't have permission to transfer, most of which were started by Rutger Vos; I have an email in to him to check on this.

**Comment by bomeara** [comment]
Only one person's repos remain.

**Comment by arlin** [comment]
Note that "tolomatic" isn't exactly legacy code.  It is the code for the live phylotastic demo at http://phylotastic-wg.cs.nmsu.edu/script/phylotastic.cgi .   The web form has a bug report link that goes straight to the legacy/tolomatic repo on github.   We need to be sure to follow any feedback from live demos
