### ISSUE TITLE
get everyone on gitter

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#39]
Create an all-hands email list.

**Comment by arlin** [comment]
We decided to do this as a gitter room.   I'll split this into sub-tasks, each with a different ticket.

**Comment by arlin** [comment]
This is the first step.  
Step 2. gitter training
Step 3.  private room, sub-rooms for teams, etc.

**Comment by arlin** [comment]
Everyone has been invited.  Still waiting to hear back from 2.  Should we invite our consultants?

**Comment by epontell** [comment]
We can. Though I really would like to learn to handle private rooms, there are discussions that I would like to have without the whole world reading.

Enrico

From:  Arlin Stoltzfus
Reply-To:  phylotastic/phylotastic
Date:  Wednesday, October 7, 2015 at 11:59 AM
To:  phylotastic/phylotastic
Subject:  Re: [phylotastic] get everyone on gitter (#39)


Everyone has been invited.  Still waiting to hear back from 2.  Should we invite our consultants?
