### ISSUE TITLE
set up gitter

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#4]

**Comment by dimus** [comment]
Arlin, can you add me to the organization team as well, looks like i need that to set up things

**Comment by arlin** [comment]
you are already listed as a member at https://github.com/orgs/phylotastic/people


On May 19, 2015, at 11:39 AM, Dmitry Mozzherin <notifications@github.com<mailto:notifications@github.com>> wrote:


Arlin, can you add me to the organization team as well, looks like i need that to set up things

—
Reply to this email directly or view it on GitHub<https://github.com/phylotastic/phylotastic/issues/4#issuecomment-103557260>.

------------
Arlin Stoltzfus (arlin@umd.edu<mailto:arlin@umd.edu>)
Research Biologist, NIST; Fellow, IBBR; Adj. Assoc. Prof., UMCP
IBBR, 9600 Gudelsky Drive, Rockville, MD, 20850
tel: 240 314 6208; web: www.molevol.org<http://www.molevol.org>

**Comment by dimus** [comment]
looks like insufficient privileges problem, I did send a request to authorize gitter for phylotastic

**Comment by arlin** [comment]
I granted the request just now
