### ISSUE TITLE
Coordinate with OToL on tree upload

### ISSUE THREAD

**Issue by bomeara** [phylotastic/phylotastic#43]

**Comment by bomeara** [comment]
Includes work on https://github.com/bomeara/prepotol package for processing trees.

**Comment by bomeara** [comment]
Managed to upload after preprocessing a 48K tree. Now exploring a way to do direct upload via html

**Comment by arlin** [comment]
I reviewed this.  Good work, Brian.   I downloaded the tree and viewed it in FigTree.  I also inspected the name-mapping.  The one question that came up was about the buttons to download the tree, which implies that there is only one.  When I looked at the tree list, I see that one is marked as preferred and the other is not.  Is the idea that every data set will have just one tree marked as the preferred tree?  Or if there were >1 preferred trees, would the interface be clearer about giving me a choice?

**Comment by bomeara** [comment]
Good point. I'm not sure about this -- could be worth filing a ticket with open tree
