### ISSUE TITLE
Use Case 8 : Android mobile application - Scanner for species names - Object OCR

### ISSUE THREAD

**Issue by bomeara** [phylotastic/phylotastic#45]
Idea is to make generic app that goes from name on page/sign (OCR), match names with GlobalNames, go to OToL, get tree (once you have gotten multiple species), get pictures from EOL.

Maybe use tesseract or some other OCR software to recognize names.

Could also pull info from EOL for a species when you first scan the name.

**Comment by arlin** [comment]
Note that GNRD already can do the OCR, and this is what Dima seemed to be recommending. 

My opinion is that this is a hugely useful app *before* we get to the phylogeny stuff-- an app that could get millions of uses per year.   Take this app to any museum or arboretum or zoo in the world, and you have an instant guide that gives you a page for each species (from EoL).  So, I think we should focus on getting that piece of the puzzle first.

**Comment by dimus** [comment]
If we can find a phone-based open source ocr library -- it would be great, then we do not need to send images across network -- just text, and resolution will work faster too

**Comment by bomeara** [comment]
Perhaps like this https://github.com/gali8/Tesseract-OCR-iOS

**Comment by bomeara** [comment]
Or this http://www.raywenderlich.com/93276/implementing-tesseract-ocr-ios

**Comment by dimus** [comment]
awesome!

**Comment by thanhnh-infinity** [comment]
Demo on Android devices

**Comment by arlin** [comment]
This is closed.  Improvements are a separate issue.
