### ISSUE TITLE
assemble design team, schedule meeting

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#5]
Identify all members and get agreement, schedule first meeting.

**Comment by arlin** [comment]
To include the PIs, Karen Cranston of OpenTree, a nominee from Arbor, and possibly someone from FuturePhy.  7 is about as big as we want this team to be, though.  

The design team is supplemented with our use-case consultants, which include Brian Sidlauskas, Ramona Walls, and Katja Schulz of EOL.

**Comment by epontell** [comment]
Sent message to Karen to check availability for doodle poll for this coming week

**Comment by epontell** [comment]
Would it be ok to start by contacting the use case experts to 1) refine the 5 use cases in the proposal 2) add additional use cases.

**Comment by epontell** [comment]
include Cindy Parr

**Comment by epontell** [comment]
Emails generated and sent - no reply received (except some automated out-of-the-office). Need to doodle poll the design team

**Comment by epontell** [comment]
Meeting scheduled for Friday 8/7 at 4pm Eastern
