### ISSUE TITLE
design test data collection

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#50]
Discuss requirements with programmers and make a plan to gather, store, annotate, evaluate, and make accessible test data.

**Comment by arlin** [comment]
What I have right now are a set of 7 cases for scraping, each of which has (1) some metadata describing the case (source, size, format, etc) and (2) a download URL that will resolve directly to a PDF or other file (local or non-local). 

The simple approach is just to have test/data/scrape/ with the metadata (files for each case, and some place to put the actual PDFs if we want to store them ourselves. 

So, at minimum (I don't want to make this too complicated), I need to know (1) where to put this directory (which repo) and (2) how to mark up the cases to support automatic processing.  Surely there are controlled vocabularies already that we could use in an xml, json, or RDF format to refer to resources and annotate the references.  

Suggestions?

**Comment by arlin** [comment]
For instance, we could use W3C's dcat schema,  a generic "data catalog" schema with a top-level catalog containing "dataset" records with various fields (title, description, etc), where each dataset can have multiple data resources ("distributions") represented by URLs.   I can enter a dataset record in a few minutes using a DCAT editor that I found online, then download in RDF/XML or turtle or json.  

<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
	xmlns:adms="http://www.w3.org/ns/adms#"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
	xmlns:dcat="http://www.w3.org/ns/dcat#"
	xmlns:store="https://dcat-editor.com/store/"
	xmlns:foaf="http://xmlns.com/foaf/0.1/"
	xmlns:odrs="http://schema.theodi.org/odrs#"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns:es="http://entrystore.org/terms/"
	xmlns:vcard="http://www.w3.org/2006/vcard/ns#"
	xmlns:dcterms="http://purl.org/dc/terms/">
<dcat:Catalog rdf:about="https://dcat-editor.com/store/126/resource/dcat">
	<dcterms:title>Phylotastic test documents</dcterms:title>
	<dcterms:description>A catalog of resources that are used as inputs in testing. </dcterms:description>
	<dcat:dataset rdf:resource="https://dcat-editor.com/store/126/resource/2"/>
	<dcat:dataset rdf:resource="https://dcat-editor.com/store/126/resource/4"/>
	<dcterms:publisher rdf:resource="https://dcat-editor.com/store/126/resource/1"/>
</dcat:Catalog>
<dcat:Dataset rdf:about="https://dcat-editor.com/store/126/resource/4">
	<dcterms:title xml:lang="en">Test case: Modeling body size evolution in Felidae under alternative phylogenetic hypotheses (article)</dcterms:title>
	<dcterms:description xml:lang="en">Open-access PDF article with text, figugres, and table listing species of felids (35) used in analysis.  This one is helpful because they do the same analysis with a subtree from the Bininda-Emonds supertree of 4K mammals, and with a felid-specific tree from Johnson, et al.  This allows us something to validate against.  Note also that this paper lists several other papers (mostly same authors) that use the Bininda-Emonds tree.  </dcterms:description>
	<dcat:distribution rdf:resource="https://dcat-editor.com/store/126/resource/5"/>
	<dcat:keyword>character analysis</dcat:keyword>
	<dcat:keyword>mammals</dcat:keyword>
</dcat:Dataset>
<dcat:Distribution rdf:about="https://dcat-editor.com/store/126/resource/5">
	<dcterms:description>PubMedCentral version of the article</dcterms:description>
	<dcat:accessURL rdf:resource="http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3032953/pdf/gmb-32-1-170.pdf"/>
	<dcterms:format>application/pdf</dcterms:format>
</dcat:Distribution>
<dcat:Dataset rdf:about="https://dcat-editor.com/store/126/resource/2">
	<dcterms:title xml:lang="en">Case study: Allometry of milk intake at peak lactation</dcterms:title>
	<dcterms:description xml:lang="en">Test case based on published original research by A. Riek including analysis of data from over 40 mammal species.</dcterms:description>
	<dcat:distribution rdf:resource="https://dcat-editor.com/store/126/resource/3"/>
	<dcat:keyword>character analysis</dcat:keyword>
	<dcat:keyword>Bininda-Emonds</dcat:keyword>
	<dcat:keyword>subtree</dcat:keyword>
	<dcat:keyword>mammals</dcat:keyword>
</dcat:Dataset>
<dcat:Distribution rdf:about="https://dcat-editor.com/store/126/resource/3">
	<dcterms:title>Allometry of milk intake at peak lactation</dcterms:title>
	<dcterms:description>Interactive link to download PDF article with text, figures, and table listing species used.  The phylogeny used for analysis is derived from the Bininda-Emonds mammal supertree.  </dcterms:description>
	<dcat:accessURL rdf:resource="https://www.researchgate.net/publication/233851685_Allometry_of_milk_intake_at_peak_lactation"/>
	<dcterms:rights>
		<odrs:RightsStatement rdf:nodeID="node1a2ije929x1">
			<odrs:attributionText>This article is copy protected but can be obtained interactively from ResearchGate</odrs:attributionText>
		</odrs:RightsStatement>
	</dcterms:rights>
</dcat:Distribution>
<foaf:Agent rdf:about="https://dcat-editor.com/store/126/resource/1">
	<foaf:name>The Phylotastic Project, http://www.phylotastic.org</foaf:name>
</foaf:Agent>

</rdf:RDF>

**Comment by bomeara** [comment]
I think the key thing is what will be best for our users to use on their own data. It could be that we have more stringent requirements than they have (i.e, perhaps using RDF will let us program automated unit tests of our code), in which case we should use whatever is best for us, but if we could find something simpler that they could also use, let's do that. For this case, do we want 1) to go from ```PDF or DOI``` to ```list of names``` to ```tree for those names```, or do we want 2) to go from ```PDF or DOI``` to ```list of names``` to ```finding the source tree``` (which may not be OpenTree's or DateLife's synthetic tree) to ```get their data``` to ```reprise their analysis using Arbor or something```? We'd clearly need a lot of metadata for the latter; for the former, just a workflow that takes a DOI or PDF and returns a tree, which we could then automatically compare with one we hand curate. If we are going for the former, I think RDF is overkill: I'd just make a repo that has PDFs in one dir, expected answers in another or something like that (actually, I'd probably do as an R package with data and testthat dir, but that's because it's what I know).

**Comment by arlin** [comment]
Maybe it would be good to do a brief analysis of requirements.  We have some inputs that are actual files or simply URLs.  We want to test for being able to read the input without choking.  That requires only a list of URLs or a directory of files.  

But immediately I began to think that we will want more than that.  For instance, in development and accuracy testing, developers will want to use small test data sets and avoid the ones with 100K names to scrape.  So I'd like to store some metadata about which test cases are the small, medium, large.  We might want to designate some files for use in scraping, and others for use in a test of some other capacity.  For this, we can get by with a directory of files (or a URL list) with a separate metadata file, e.g., a csv table with columns for size, etc.  

Then, going further, we will have some kinds of tests where we are not just asking whether the software chokes or not, but whether it is accurate.  In that case, we have one resource for an input and a second resource that represents the desired output (e.g., the expected tree, the expected list of names from scraping).  If we want to support automation for this kind of test regime, we need a way to pair up the input files with the output files.  Alternatively, we can just let the programmers do that by hand when coding up individual tests.

**Comment by bomeara** [comment]
A dir of files and a csv of properties makes a lot of sense to me -- low key at first, can get richer as we need it to, and if need it to go nuts and RDF/SQL/etc. we could process the csv once with a script to set this up.

**Comment by arlin** [comment]
That's what I was thinking, too.  I think I will need project-specific id, name of resource, URL-or-local_file, location, file format, mime type, order-of-magnitude size, reference, free-form description.

**Comment by arlin** [comment]
Where shall I put the test data?   Is every phylotastic app going to have a separate repo?   Do we want to avoid proliferation of repos?  I have no experience with this question.   For now, I'm going to put it in the phylotastic.github.io repo, because that's what I'm used to using (and some of the test files live there).

**Comment by bomeara** [comment]
I think every app would have its own repo, but we should in general try to keep the number of repos low -- when we add new people, or for others watching our progress, make it simple for them to figure out what we're up to.
