### ISSUE TITLE
evaluate pivotal tracker

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#53]
see #51 for criteria. Add results to the table at: https://github.com/phylotastic/phylotastic.github.io/blob/master/docs/tracker_evaluations.csv

**Comment by dimus** [comment]
Pivotal Tracker is one  of the first decent Agile tools

Github
---------

### Pros
- Connection to Github [can be made](http://www.pivotaltracker.com/community/tracker-blog/guide-githubs-service-hook-tracker)

### Cons
- Connection to Github is less intuitive and seamless than with Waffle or ZenHub
 
Agile
------

### Pros
- 'Kanban' board from the day one. It is quite intuitive and much more poverful than Waffle/ZenHub
- A lot of powerful agile tools -- automatic calculation of all important statistics, flexible tracking of velocity. Much more mature from Agile standpoint than Waffle of ZenHub

### Cons
- It is so Agile that sometimes it stand on its way when you there is a need to do things differently
- Iterations are not very flexible, it is combersome to change size on iteration, or date of iteration.

Multiple projects:
-----------------------

-Looks like there is [multiproject view](http://www.pivotaltracker.com/community/tracker-blog/wonders-workspaces)

Personal preference
---------------------------

I did like to work with Pivotal tracker in the past, and I did like it better than Jira. However I feel too removed from my repository there, whild with ZenHub and Waffle I am very tightly intergrated with the repository -- which means I am not switching back and forth between two systems. And this is a killer feature for me.
So inspite of all niceties of Pivotal tracker -- more primitive projects like Waffle and Zenhub are better for me

**Comment by arlin** [comment]
Thanks, Dima.  I put these comments into the spreadsheet for trackers.  We'll get back to this at some later date.
