### ISSUE TITLE
evaluate zenhub tracker

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#54]
see #51 for criteria. Add results to the table at: https://github.com/phylotastic/phylotastic.github.io/blob/master/docs/tracker_evaluations.csv

**Comment by dimus** [comment]
I worked this week in both Waffle and ZenHub. Here are my impressions about ZenHub:

General
----------

### Pros
- Free for open source
- Everybody who cares can come and see without special password etc.

### Cons
Plugin access only


Integration with Github
------------------------------

### Pros
- Seamless integration into GitHub (no separate site to go)
- Tickets window uses the same code ads Github (which is more stable, and also -- one less thing to remember)
- Markdown, automated issues closing, automated links to people
- Streamlined -- very few things to learn

### Cons

- To see it people need too install ZenHub plugin
- Only Chrome
- Board sometimes gets 'stuck'
- Less intuitive integration of pull requests with issues

Agile
------

### Pros
- Very flexible burndown graph (iterations can be set by start and end date, no magic)
- Kanban board is nice, more flexible, and has IMO better organization (Kanban term might be a bit misleading -- as Kanban is a 'reactive' flavor of Agile, more suitable for sys admins than  for programmers)
-  Process is very streamlined

### Cons
- Not all Agile components are implemented -- most notably there is no velocity graph
- Burndown uses milestones as a hack, which means team can either have milestones, or iterations, not both.
- not sublevel (tasks) or superlevel (epoches) -- only stories. 

Multiproject integration
------------------------------

### Pros
- Allows to work on several projects at the same time and combine projects flexibly
- Allows to mix and match repositories, with show all, show one shortcut

### Cons
- No visual separation of projects -- all tickets mixed together
- No ability to have super board (board must start with a project)
- No ability to join projects from other organizations


Conclustion
----------------

It is my personal winner, but it is far from perfect

**Comment by arlin** [comment]
Thanks.  I linked this content into the spreadsheet file for tracker evaluations.
