### ISSUE TITLE
DateLife example not working

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#64]
The DateLife web services snippet at phylotastic.org 

 http://datelife.org/cgi-bin/R/result?taxa=Rhinoceros_unicornis%2CEquus_caballus%2CMus_musculus&format=newickmed&partial=liberal&useembargoed=no&uncertainty=100

does not work.  It returns "Unable to connect (result=-1, socket:unknown socket error 2)."

**Comment by bomeara** [comment]
Refactoring the datelife code; will create new issues once done.
