### ISSUE TITLE
set up web site to mirror phylotastic.github.io

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#7]
This was set up previously at NESCent so that the web site content would get updated whenever the github repo is updated.

**Comment by arlin** [comment]
Not sure if this helps, but github has a "webhooks" feature that will send a POST when something gets changed in the repo.  This might be useful to automate the updating.  See https://github.com/phylotastic/phylotastic.github.io/settings/hooks

**Comment by arlin** [comment]
Enrico, I made a small change to the "About" page, mentioning that NSF is funding the project and we are hiring.  You can use this change to test if the web site is getting updated.

**Comment by arlin** [comment]
I further updated the "About" page to include a link to the grant proposal, which is now in the "docs" folder.

**Comment by epontell** [comment]
Web site is up and running. It is pulling each hour content from github and transferring it to the NMSU side.
