### ISSUE TITLE
Start testing services

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#71]
Start testing services on a daily or weekly basis for availability and performance.  Establish a baseline for improvements in reliability and performance.  Start with OpenTree, TreeBASE, GN, iPlantTNRS, and any services that we are standing up.  Contact the service owners and explain what we are doing and why.

**Comment by arlin** [comment]
Does PhyloCommons have a web api?  Ask Ben.

**Comment by arlin** [comment]
There is a sketch of an overall testing strategy here: https://github.com/phylotastic/phylotastic/blob/master/testing/test_strategy_notes.md

**Comment by bomeara** [comment]
Looks good, Arlin. I'd suggest thinking about how to make sure you're not calling cached results. Especially for common queries, services will be smart to cache results (until the underlying tree changes), but presumably we want to test new queries, too. So it means asking for new things each time. The alternative is having some way to reset cached results.

**Comment by arlin** [comment]
Good point about cached results.   Perhaps we need every service to have a no-cached  option, or to have a test-mode option that is invoked only by robots performing regular tests.

**Comment by hdliv** [comment]
We have started testing the web portal

**Comment by arlin** [comment]
@hdliv, thanks for doing that, but this ticket is about running automated tests on the back-end services to establish their reliability and accuracy.

**Comment by hdliv** [comment]
crontab running everyday at 8:30

**Comment by hdliv** [comment]
@thanhnh-infinity Aren't we currently testing with TRAVIS?

**Comment by thanhnh-infinity** [comment]
Hi @hdliv , all our services are testing with Travis. It will automatic test when new source code is updated in Github. Abu and I are working on schedule testing daily, It will be updated soon
