### ISSUE TITLE
Create web service to retrieve all or some species from a taxon

### ISSUE THREAD

**Issue by abusalehmdtayeen** [phylotastic/phylotastic#74]

**Comment by abusalehmdtayeen** [comment]
Finished coding a service to retrieve all species from taxon name. It needs to be hosted once the server is ready.

**Comment by arlin** [comment]
That sounds good.  We would be happy to evaluate that and suggest useful options.

**Comment by abusalehmdtayeen** [comment]
Service has been hosted and publicly live.

**Comment by abusalehmdtayeen** [comment]
Service Name: Get All Species from a Taxon

Resource URI: http://phylo.cs.nmsu.edu:5004/phylotastic_ws/ts/all_species

Parameters: taxon (Mandatory)
                   - name of the taxon for which all species will be retrieved

Examples:
http://phylo.cs.nmsu.edu:5004/phylotastic_ws/ts/all_species?taxon=Vulpes
http://phylo.cs.nmsu.edu:5004/phylotastic_ws/ts/all_species?taxon=Panthera
http://phylo.cs.nmsu.edu:5004/phylotastic_ws/ts/all_species?taxon=Canidae

Please let me know if any taxon name does not give correct output or gives error.

**Comment by arlin** [comment]
Thanks.  This is good!   Two challenges are (1) Some of the queries take a long time, e.g., 30 s and (2) OpenTree's taxonomy contains extinct species, e.g., "Felidae" is mostly extinct genera  like Smilodon (saber-toothed cat) and Pseudaelurus.
