### ISSUE TITLE
Complete Mobile App on Android

### ISSUE THREAD

**Issue by epontell** [phylotastic/phylotastic#80]

**Comment by epontell** [comment]
Need to determine how to distribute an Android App to all team members

**Comment by arlin** [comment]
Is there a mobile app repo?  If so, this ticket should be in the mobile app repo, rather than phylotastic/phylotastic.

**Comment by arlin** [comment]
Yes, we should close this ticket and create an identical one in phylotastic/Phylotastic_Mobile_Application.  Enrico, do you want to do that, or shall I?

**Comment by thanhnh-infinity** [comment]
I pushed : Android OCR and Android QR  Source Code into Github : phylotastic/Phylotastic_Mobile_Application
