### ISSUE TITLE
Develop IOS version of the App

### ISSUE THREAD

**Issue by epontell** [phylotastic/phylotastic#81]
Need to get license and do porting
Figure out how to disseminate without using App store

**Comment by arlin** [comment]
We should close this ticket and open an identical one in phylotastic/Phylotastic_Mobile_Application.

**Comment by thanhnh-infinity** [comment]
I will develop it immediately when I have  Apple license and device.

**Comment by epontell** [comment]
Apple license has been acquired. Looking for a device.

**Comment by epontell** [comment]
iPhone 5s ordered - should be here early next week.

**Comment by arlin** [comment]
the iPhone app was demo'ed by Thanh today, so I'm going to move this ticket.
