### ISSUE TITLE
Set up Open Service Registry

### ISSUE THREAD

**Issue by epontell** [phylotastic/phylotastic#88]

**Comment by epontell** [comment]
Server has been acquired.
Abu Saleh will install Ubuntu, Drupal
Abu Saleh and Thanh together move service registry and services from old server to the new one

**Comment by thanhnh-infinity** [comment]
I will collaborate with Abu to move them.

**Comment by abusalehmdtayeen** [comment]
OS and software installed. Service registry and services has been moved from old to new server. Need to configure settings and test the services.
