### ISSUE TITLE
Continue Research about Web Semantics Composition and Ontology

### ISSUE THREAD

**Issue by thanhnh-infinity** [phylotastic/phylotastic#89]

**Comment by thanhnh-infinity** [comment]
Reading paper : An Agent-Based Domain Specific Framework for Rapid Prototyping of Applications in Evolutionary Biology

**Comment by thanhnh-infinity** [comment]
Reading paper : Answer Set Programming for the Semantic Web - Thomas Eiter

**Comment by hdliv** [comment]
@thanhnh-infinity Have you finished this ticket?  If so maybe we can move this to done.  Thanks

**Comment by thanhnh-infinity** [comment]
I have not finished this ticket. Let me update this ticket after discuss with Dr Pontelli
