### ISSUE TITLE
Create initial use cases

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic#94]
provide 5 initial user cases

**Comment by arlin** [comment]
Thanks.  Please tell folks where to find them.

**Comment by hdliv** [comment]
these use cases can be found: phylotastic/phylotastic-portal/use_cases/

**Comment by arlin** [comment]
Dail, once you have the initial use-cases available via github, this ticket is closed.  Adding other use-cases would be a separate task.

**Comment by hdliv** [comment]
OK.  I thought we had to review them before closing.
