### ISSUE TITLE
Refactor DateLife code

### ISSUE THREAD

**Issue by bomeara** [phylotastic/phylotastic#99]
Separate DateLife into an R pkg with core functionality and web view into that.

**Comment by bomeara** [comment]
I've created a datelife-web repo to store the php and related code, and started refactoring the datelife repo to be a basic R package. Will eventually add tests and such.

**Comment by arlin** [comment]
@bomeara, what's the status of this?  I have seen a lot of other datelife tickets get closed that involved tests and re-factoring.  Is this really a milestone rather than a ticket?

**Comment by bomeara** [comment]
I'm not sure about the milestone / ticket distinction. But it's done.
